package io.github.vhow.animation.principles;

public enum Principle {
    SQUASH_AND_STRETCH,
    ANTICIPATION,
    STAGING,
    STRAIGHT_AHEAD_ACTION_AND_POSE_TO_POSE,
    FOLLOW_THROUGH_AND_OVERLAPPING_ACTION,
    SLOW_IN_AND_SLOW_OUT,
    ARC,
    SECONDARY_ACTION,
    TIMING,
    EXAGGERATION,
    SOLID_DRAWING,
    APPEAL
}
